
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set branch name
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo " docker build -t myapp:${BRANCH_NAME}-${{ github.sha }}"
